// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import Image from './Image';
import Markdown from './Markdown';
import Quote from './Quote';
import RichText from './RichText';

export {
	ContactForm,
	Image,
	Markdown,
	Quote,
	RichText,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	text: Markdown,
	quote: Quote,
	rich_text: RichText,
};
